workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      groups:
        - ios_credentials
        - appstore_credentials
      ios_signing:
        # distribution_type: app_store
        # bundle_identifier: com.example.syringePumpApp
        provisioning_profiles:
          - Syringe_App
        certificates:
          - iOS_Distribution_Certificate
    scripts:
      - name: Install npm dependencies and update Cordova version
        script: | 
          npm install
          npm install -g cordova
      -  name: Setup Cordova iOS platform
         script: | 
           cordova platform remove ios --nosave
           cordova platform add ios \
             --confirm \
             --no-interactive \
             --noresources \
             --save
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles --project platforms/ios/CordovaSyringePumpApp.xcodeproj
      - name: Build ipa for distribution
        script: | 
          cat /Users/builder/export_options.plist
          package_type=$(defaults read /Users/builder/export_options.plist method)
          identity=$(defaults read /Users/builder/export_options.plist signingCertificate)
          team=$(defaults read /Users/builder/export_options.plist teamID)
          profile=$(find '/Users/builder/Library/MobileDevice/Provisioning Profiles' -name "*.mobileprovision")
          profile_uuid=$(grep UUID -A1 -a "$profile" | grep -io "[-A-F0-9]\{36\}")

          echo $package_type
          echo $identity
          echo $team
          echo $profile
          echo $profile_uuid

          cat > build.json <<EOF
          {
            "ios": {
              "release": {
                "codeSignIdentity": "$identity",
                "developmentTeam": "$team",
                "packageType": "$package_type",
                "provisioningProfile": "$profile_uuid"
              }
            }
          }
          EOF
          cat build.json
          echo "About to build"
          cordova build ios --release --device --buildConfig='build.json'
    artifacts:
      - /Users/builder/clone/platforms/ios/build/Release-iphoneos/CordovaSyringePumpApp.ipa
      - /tmp/xcodebuild_logs/*.log 
    publishing:
      email:
        recipients:
          - alimidammy02@gmail.com
        notify:
          success: true
          failure: false